baseURL: "https://www.streltcova.art"
languageCode: "en-us"
title: "Natalia Streltcova"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Natalia Streltcova"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Natalia Streltcova" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Natalia."
    subtitle: "I create things for a living"
    content: "I am very pleased to welcome you to my website. Browse a little and simply let yourself be inspired."
    image: /images/hero.png
    button:
      enable: true
      name: "More..."
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/TCL-Books/website-nata
        - icon: fab fa-instagram
          url: https://example.com
  #    customIcons:
  #      - icon: /fav.png
  #        url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      My name is Natalia Streltcova. For over 10 years, I have been working as a freelance artist and painter. Art has always been my passion.
      Already as a child, I liked to paint. My parents always supported me and encouraged me in my decision. Fortunately, I’ve never regretted it.

      I am fascinated by simple things that surround us – sunset, colorful leaves in autumn, a small flower in the field or a stream lined with
      trees. Or my children who are very lively and curious and invent or discover something new every minute. All this flows into my artwork.
    skills:
      enable: true
      title: "Here are a few techniques I've been working with recently:"
      items:
        - "Found art"
        - "Wet and dry media"
        - "Collage"
        - "Découpage"
        - "Assemblage"
        - "Book alteration"

  # Techniques
  education:
    enable: true
    title: "Techniques"
    index: false
    items:
      - title: "Mixed Media"
        school:
          name: "More information"
          url: "https://de.wikipedia.org/wiki/Mixed_Media"
        content: |-
          In the visual arts, the term mixed media stands for using different media in the creation of a work.
          
          An example of mixed media is integrating graphic elements in a painting on the same painting surface: this is then neither a collage nor
          multimedia.
          
          Especially with adhesive techniques, it is important to allow the individual layers to dry well and to apply oil paint, if used, last. When
          using many or heavy materials, the painting ground should be particularly firm, wood is often used.
        featuredLink:
          enable: true
          name: "My works"
          url: "https://example.com"
      - title: "Encaustic Mixed Media"
        school:
          name: "More information"
          url: "https://allthingsencaustic.com/encaustic-collage/"
        content: |-
          The technique has a much longer tradition than oil painting. It experienced its heyday in the art of Greek-Roman antiquity. In the artists'
          imagination, their own materialized thoughts were burned imperishably onto the painting surface with fire. The word encaustic has also been
          used for more than two and a half millennia and is derived from the Greek word enkauston, burned in, which in turn is derived from enkaio,
          to burn in.
        featuredLink:
          enable: true
          name: "My works"
          url: "https://example.com"
      - title: "Additional Section"
        school:
          name: "Maybe some text about painting."
          url: "https://example.org"
        featuredLink:
          enable: true
          name: "My works"
          url: "https://example.com"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: myemail@gmail.com
    btnName: Mail me

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/TCL-Books/website-nata
      twitter: https://twitter.com
      instagram: https://instagram.com/natalia_art_gallery?igshid=uohg3sqa5nzf
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
